package com.mybatis.mybatisgeneratordemo.model;

import java.io.Serializable;
import java.util.Date;

public class Problem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problem.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problem.pbm_num
     *
     * @mbg.generated
     */
    private String pbmNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problem.pbm_desc
     *
     * @mbg.generated
     */
    private String pbmDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problem.pbm_owner
     *
     * @mbg.generated
     */
    private String pbmOwner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problem.pbm_creater
     *
     * @mbg.generated
     */
    private String pbmCreater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problem.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problem.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problem.id
     *
     * @return the value of t_problem.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    public Problem withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problem.id
     *
     * @param id the value for t_problem.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problem.pbm_num
     *
     * @return the value of t_problem.pbm_num
     *
     * @mbg.generated
     */
    public String getPbmNum() {
        return pbmNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    public Problem withPbmNum(String pbmNum) {
        this.setPbmNum(pbmNum);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problem.pbm_num
     *
     * @param pbmNum the value for t_problem.pbm_num
     *
     * @mbg.generated
     */
    public void setPbmNum(String pbmNum) {
        this.pbmNum = pbmNum == null ? null : pbmNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problem.pbm_desc
     *
     * @return the value of t_problem.pbm_desc
     *
     * @mbg.generated
     */
    public String getPbmDesc() {
        return pbmDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    public Problem withPbmDesc(String pbmDesc) {
        this.setPbmDesc(pbmDesc);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problem.pbm_desc
     *
     * @param pbmDesc the value for t_problem.pbm_desc
     *
     * @mbg.generated
     */
    public void setPbmDesc(String pbmDesc) {
        this.pbmDesc = pbmDesc == null ? null : pbmDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problem.pbm_owner
     *
     * @return the value of t_problem.pbm_owner
     *
     * @mbg.generated
     */
    public String getPbmOwner() {
        return pbmOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    public Problem withPbmOwner(String pbmOwner) {
        this.setPbmOwner(pbmOwner);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problem.pbm_owner
     *
     * @param pbmOwner the value for t_problem.pbm_owner
     *
     * @mbg.generated
     */
    public void setPbmOwner(String pbmOwner) {
        this.pbmOwner = pbmOwner == null ? null : pbmOwner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problem.pbm_creater
     *
     * @return the value of t_problem.pbm_creater
     *
     * @mbg.generated
     */
    public String getPbmCreater() {
        return pbmCreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    public Problem withPbmCreater(String pbmCreater) {
        this.setPbmCreater(pbmCreater);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problem.pbm_creater
     *
     * @param pbmCreater the value for t_problem.pbm_creater
     *
     * @mbg.generated
     */
    public void setPbmCreater(String pbmCreater) {
        this.pbmCreater = pbmCreater == null ? null : pbmCreater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problem.create_time
     *
     * @return the value of t_problem.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    public Problem withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problem.create_time
     *
     * @param createTime the value for t_problem.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problem.update_time
     *
     * @return the value of t_problem.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    public Problem withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problem.update_time
     *
     * @param updateTime the value for t_problem.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pbmNum=").append(pbmNum);
        sb.append(", pbmDesc=").append(pbmDesc);
        sb.append(", pbmOwner=").append(pbmOwner);
        sb.append(", pbmCreater=").append(pbmCreater);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}