package com.mybatis.mybatisgeneratordemo.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProblemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    public ProblemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPbmNumIsNull() {
            addCriterion("pbm_num is null");
            return (Criteria) this;
        }

        public Criteria andPbmNumIsNotNull() {
            addCriterion("pbm_num is not null");
            return (Criteria) this;
        }

        public Criteria andPbmNumEqualTo(String value) {
            addCriterion("pbm_num =", value, "pbmNum");
            return (Criteria) this;
        }

        public Criteria andPbmNumNotEqualTo(String value) {
            addCriterion("pbm_num <>", value, "pbmNum");
            return (Criteria) this;
        }

        public Criteria andPbmNumGreaterThan(String value) {
            addCriterion("pbm_num >", value, "pbmNum");
            return (Criteria) this;
        }

        public Criteria andPbmNumGreaterThanOrEqualTo(String value) {
            addCriterion("pbm_num >=", value, "pbmNum");
            return (Criteria) this;
        }

        public Criteria andPbmNumLessThan(String value) {
            addCriterion("pbm_num <", value, "pbmNum");
            return (Criteria) this;
        }

        public Criteria andPbmNumLessThanOrEqualTo(String value) {
            addCriterion("pbm_num <=", value, "pbmNum");
            return (Criteria) this;
        }

        public Criteria andPbmNumLike(String value) {
            addCriterion("pbm_num like", value, "pbmNum");
            return (Criteria) this;
        }

        public Criteria andPbmNumNotLike(String value) {
            addCriterion("pbm_num not like", value, "pbmNum");
            return (Criteria) this;
        }

        public Criteria andPbmNumIn(List<String> values) {
            addCriterion("pbm_num in", values, "pbmNum");
            return (Criteria) this;
        }

        public Criteria andPbmNumNotIn(List<String> values) {
            addCriterion("pbm_num not in", values, "pbmNum");
            return (Criteria) this;
        }

        public Criteria andPbmNumBetween(String value1, String value2) {
            addCriterion("pbm_num between", value1, value2, "pbmNum");
            return (Criteria) this;
        }

        public Criteria andPbmNumNotBetween(String value1, String value2) {
            addCriterion("pbm_num not between", value1, value2, "pbmNum");
            return (Criteria) this;
        }

        public Criteria andPbmDescIsNull() {
            addCriterion("pbm_desc is null");
            return (Criteria) this;
        }

        public Criteria andPbmDescIsNotNull() {
            addCriterion("pbm_desc is not null");
            return (Criteria) this;
        }

        public Criteria andPbmDescEqualTo(String value) {
            addCriterion("pbm_desc =", value, "pbmDesc");
            return (Criteria) this;
        }

        public Criteria andPbmDescNotEqualTo(String value) {
            addCriterion("pbm_desc <>", value, "pbmDesc");
            return (Criteria) this;
        }

        public Criteria andPbmDescGreaterThan(String value) {
            addCriterion("pbm_desc >", value, "pbmDesc");
            return (Criteria) this;
        }

        public Criteria andPbmDescGreaterThanOrEqualTo(String value) {
            addCriterion("pbm_desc >=", value, "pbmDesc");
            return (Criteria) this;
        }

        public Criteria andPbmDescLessThan(String value) {
            addCriterion("pbm_desc <", value, "pbmDesc");
            return (Criteria) this;
        }

        public Criteria andPbmDescLessThanOrEqualTo(String value) {
            addCriterion("pbm_desc <=", value, "pbmDesc");
            return (Criteria) this;
        }

        public Criteria andPbmDescLike(String value) {
            addCriterion("pbm_desc like", value, "pbmDesc");
            return (Criteria) this;
        }

        public Criteria andPbmDescNotLike(String value) {
            addCriterion("pbm_desc not like", value, "pbmDesc");
            return (Criteria) this;
        }

        public Criteria andPbmDescIn(List<String> values) {
            addCriterion("pbm_desc in", values, "pbmDesc");
            return (Criteria) this;
        }

        public Criteria andPbmDescNotIn(List<String> values) {
            addCriterion("pbm_desc not in", values, "pbmDesc");
            return (Criteria) this;
        }

        public Criteria andPbmDescBetween(String value1, String value2) {
            addCriterion("pbm_desc between", value1, value2, "pbmDesc");
            return (Criteria) this;
        }

        public Criteria andPbmDescNotBetween(String value1, String value2) {
            addCriterion("pbm_desc not between", value1, value2, "pbmDesc");
            return (Criteria) this;
        }

        public Criteria andPbmOwnerIsNull() {
            addCriterion("pbm_owner is null");
            return (Criteria) this;
        }

        public Criteria andPbmOwnerIsNotNull() {
            addCriterion("pbm_owner is not null");
            return (Criteria) this;
        }

        public Criteria andPbmOwnerEqualTo(String value) {
            addCriterion("pbm_owner =", value, "pbmOwner");
            return (Criteria) this;
        }

        public Criteria andPbmOwnerNotEqualTo(String value) {
            addCriterion("pbm_owner <>", value, "pbmOwner");
            return (Criteria) this;
        }

        public Criteria andPbmOwnerGreaterThan(String value) {
            addCriterion("pbm_owner >", value, "pbmOwner");
            return (Criteria) this;
        }

        public Criteria andPbmOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("pbm_owner >=", value, "pbmOwner");
            return (Criteria) this;
        }

        public Criteria andPbmOwnerLessThan(String value) {
            addCriterion("pbm_owner <", value, "pbmOwner");
            return (Criteria) this;
        }

        public Criteria andPbmOwnerLessThanOrEqualTo(String value) {
            addCriterion("pbm_owner <=", value, "pbmOwner");
            return (Criteria) this;
        }

        public Criteria andPbmOwnerLike(String value) {
            addCriterion("pbm_owner like", value, "pbmOwner");
            return (Criteria) this;
        }

        public Criteria andPbmOwnerNotLike(String value) {
            addCriterion("pbm_owner not like", value, "pbmOwner");
            return (Criteria) this;
        }

        public Criteria andPbmOwnerIn(List<String> values) {
            addCriterion("pbm_owner in", values, "pbmOwner");
            return (Criteria) this;
        }

        public Criteria andPbmOwnerNotIn(List<String> values) {
            addCriterion("pbm_owner not in", values, "pbmOwner");
            return (Criteria) this;
        }

        public Criteria andPbmOwnerBetween(String value1, String value2) {
            addCriterion("pbm_owner between", value1, value2, "pbmOwner");
            return (Criteria) this;
        }

        public Criteria andPbmOwnerNotBetween(String value1, String value2) {
            addCriterion("pbm_owner not between", value1, value2, "pbmOwner");
            return (Criteria) this;
        }

        public Criteria andPbmCreaterIsNull() {
            addCriterion("pbm_creater is null");
            return (Criteria) this;
        }

        public Criteria andPbmCreaterIsNotNull() {
            addCriterion("pbm_creater is not null");
            return (Criteria) this;
        }

        public Criteria andPbmCreaterEqualTo(String value) {
            addCriterion("pbm_creater =", value, "pbmCreater");
            return (Criteria) this;
        }

        public Criteria andPbmCreaterNotEqualTo(String value) {
            addCriterion("pbm_creater <>", value, "pbmCreater");
            return (Criteria) this;
        }

        public Criteria andPbmCreaterGreaterThan(String value) {
            addCriterion("pbm_creater >", value, "pbmCreater");
            return (Criteria) this;
        }

        public Criteria andPbmCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("pbm_creater >=", value, "pbmCreater");
            return (Criteria) this;
        }

        public Criteria andPbmCreaterLessThan(String value) {
            addCriterion("pbm_creater <", value, "pbmCreater");
            return (Criteria) this;
        }

        public Criteria andPbmCreaterLessThanOrEqualTo(String value) {
            addCriterion("pbm_creater <=", value, "pbmCreater");
            return (Criteria) this;
        }

        public Criteria andPbmCreaterLike(String value) {
            addCriterion("pbm_creater like", value, "pbmCreater");
            return (Criteria) this;
        }

        public Criteria andPbmCreaterNotLike(String value) {
            addCriterion("pbm_creater not like", value, "pbmCreater");
            return (Criteria) this;
        }

        public Criteria andPbmCreaterIn(List<String> values) {
            addCriterion("pbm_creater in", values, "pbmCreater");
            return (Criteria) this;
        }

        public Criteria andPbmCreaterNotIn(List<String> values) {
            addCriterion("pbm_creater not in", values, "pbmCreater");
            return (Criteria) this;
        }

        public Criteria andPbmCreaterBetween(String value1, String value2) {
            addCriterion("pbm_creater between", value1, value2, "pbmCreater");
            return (Criteria) this;
        }

        public Criteria andPbmCreaterNotBetween(String value1, String value2) {
            addCriterion("pbm_creater not between", value1, value2, "pbmCreater");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_problem
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_problem
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}